environment:
  matrix:
    - node_version: "8"
    - node_version: "6"
    - node_version: "4"

branches:
  only:
  - master
  - appveyor
  
install:
  - ps: Install-Product node $env:node_version
  - yarn install

test_script:
  - node --version
  - yarn run coveralls
  
cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"
