environment:
  matrix:
    - node_version: "8"

build: off

branches:
  only:
  - appveyor
  
install:
  - ps: Install-Product node $env:node_version
  - yarn install

test_script:
  - node --version
  - yarn run test
  
cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"
